### ISSUE TITLE
[BUG] Null pointer upon retrieving WorldSavedData in horse code

### ISSUE THREAD

**Issue by 0xfrej** [Lai0n/Wiedzminstvo#12]
[21:52:09] [Server thread/ERROR] [ne.mi.ev.EventBus/EVENTBUS]: Exception caught during firing event: null
	Index: 1
	Listeners:
		0: NORMAL
		1: ASM: dev.sharpwave.wiedzminstvo.entity.events.HorseEntityEvents@19389485 onStopTracking(Lnet/minecraftforge/event/entity/player/PlayerEvent$StopTracking;)V
java.lang.NullPointerException
	at dev.sharpwave.wiedzminstvo.utils.Storage.getStorageInstance(Storage.kt:16)
	at dev.sharpwave.wiedzminstvo.world.data.HorsesWorldData$Companion.getInstance(HorsesWorldData.kt:127)
	at dev.sharpwave.wiedzminstvo.utils.HorseHelper.getWorldData(HorseHelper.kt:87)
	at dev.sharpwave.wiedzminstvo.entity.managers.HorseManager.saveHorse(HorseManager.kt:355)
	at dev.sharpwave.wiedzminstvo.entity.events.HorseEntityEvents.onStopTracking(HorseEntityEvents.kt:129)
	at net.minecraftforge.eventbus.ASMEventHandler_21_HorseEntityEvents_onStopTracking_StopTracking.invoke(.dynamic)
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85)
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302)
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283)
	at net.minecraftforge.event.ForgeEventFactory.onStopEntityTracking(ForgeEventFactory.java:336)
	at net.minecraft.world.TrackedEntity.removePairing(TrackedEntity.java:189)
	at net.minecraft.world.server.ChunkManager$EntityTracker.removePlayer(ChunkManager.java:1139)
	at net.minecraft.world.server.ChunkManager.removeEntity(ChunkManager.java:985)
	at net.minecraft.world.server.ServerChunkProvider.removeEntity(ServerChunkProvider.java:454)
	at net.minecraft.world.server.ServerWorld.removeEntityComplete(ServerWorld.java:905)
	at net.minecraft.world.server.ServerWorld.removeEntity(ServerWorld.java:951)
	at net.minecraft.world.server.ServerWorld.removePlayer(ServerWorld.java:968)
	at net.minecraft.world.server.ServerWorld.removePlayerImmediately(ServerWorld.java:964)
	at net.minecraft.server.management.PlayerList.remove(PlayerList.java:338)
	at net.minecraft.network.play.ServerPlayNetHandler.onDisconnect(ServerPlayNetHandler.java:1021)
	at net.minecraft.network.NetworkManager.handleDisconnection(NetworkManager.java:368)
	at net.minecraft.network.NetworkSystem.tick(NetworkSystem.java:149)
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:865)
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:787)
	at net.minecraft.server.integrated.IntegratedServer.tickServer(IntegratedServer.java:78)
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:642)
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:232)
	at java.lang.Thread.run(Thread.java:748)

[21:52:09] [Server thread/ERROR] [minecraft/MinecraftServer]: Encountered an unexpected exception
java.lang.NullPointerException: null
	at dev.sharpwave.wiedzminstvo.utils.Storage.getStorageInstance(Storage.kt:16) ~[main/:?] {re:classloading}
	at dev.sharpwave.wiedzminstvo.world.data.HorsesWorldData$Companion.getInstance(HorsesWorldData.kt:127) ~[main/:?] {re:classloading}
	at dev.sharpwave.wiedzminstvo.utils.HorseHelper.getWorldData(HorseHelper.kt:87) ~[main/:?] {re:classloading}
	at dev.sharpwave.wiedzminstvo.entity.managers.HorseManager.saveHorse(HorseManager.kt:355) ~[main/:?] {re:classloading}
	at dev.sharpwave.wiedzminstvo.entity.events.HorseEntityEvents.onStopTracking(HorseEntityEvents.kt:129) ~[main/:?] {re:classloading}
	at net.minecraftforge.eventbus.ASMEventHandler_21_HorseEntityEvents_onStopTracking_StopTracking.invoke(.dynamic) ~[?:?] {}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.event.ForgeEventFactory.onStopEntityTracking(ForgeEventFactory.java:336) ~[forge:?] {re:classloading}
	at net.minecraft.world.TrackedEntity.removePairing(TrackedEntity.java:189) ~[forge:?] {re:classloading}
	at net.minecraft.world.server.ChunkManager$EntityTracker.removePlayer(ChunkManager.java:1139) ~[forge:?] {re:classloading}
	at net.minecraft.world.server.ChunkManager.removeEntity(ChunkManager.java:985) ~[forge:?] {re:classloading}
	at net.minecraft.world.server.ServerChunkProvider.removeEntity(ServerChunkProvider.java:454) ~[forge:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.world.server.ServerWorld.removeEntityComplete(ServerWorld.java:905) ~[forge:?] {re:classloading}
	at net.minecraft.world.server.ServerWorld.removeEntity(ServerWorld.java:951) ~[forge:?] {re:classloading}
	at net.minecraft.world.server.ServerWorld.removePlayer(ServerWorld.java:968) ~[forge:?] {re:classloading}
	at net.minecraft.world.server.ServerWorld.removePlayerImmediately(ServerWorld.java:964) ~[forge:?] {re:classloading}
	at net.minecraft.server.management.PlayerList.remove(PlayerList.java:338) ~[forge:?] {re:classloading}
	at net.minecraft.network.play.ServerPlayNetHandler.onDisconnect(ServerPlayNetHandler.java:1021) ~[forge:?] {re:classloading}
	at net.minecraft.network.NetworkManager.handleDisconnection(NetworkManager.java:368) ~[forge:?] {re:classloading}
	at net.minecraft.network.NetworkSystem.tick(NetworkSystem.java:149) ~[forge:?] {re:classloading}
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:865) ~[forge:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:787) ~[forge:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.integrated.IntegratedServer.tickServer(IntegratedServer.java:78) ~[forge:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:642) ~[forge:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:232) ~[forge:?] {re:classloading,pl:accesstransformer:B}
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_302] {}
[21:52:09] [Server thread/FATAL] [ne.mi.co.ForgeMod/]: Preparing crash report with UUID add5bf7a-56b8-4b0d-aa7f-9c31730392d5
AL lib: (EE) alc_cleanup: 1 device not closed

Process finished with exit code -1

**Comment by Lai0n** [comment]
Found missing assignment in `dev.sharpwave.wiedzminstvo.utils.Storage.getStorageInstance`, which caused the null pointer exception
